language: emacs-lisp
sudo: false
env:
  global:
  - EMAKE_SHA1=2dec3626e073c3b4aa88fbedd7ad5d27e530f470
  matrix:
  - EMACS_VERSION=25.1
  - EMACS_VERSION=25.2
  - EMACS_VERSION=25.3
  - EMACS_VERSION=26.1
  - EMACS_VERSION=snapshot
before_install:
  - wget "https://raw.githubusercontent.com/vermiculus/emake.el/${EMAKE_SHA1}/emake.mk"
  - make setup
install:
  - make install
script:
  - make test         # test uncompiled
  - make compile
  - make test         # test compiled
