language: emacs-lisp
sudo: false
env:
  global:
  - EMAKE_SHA1=ef8e31c979ca6d084f20ccc975c5fc6d22dd31b9
  - EMACS_DIR=$HOME/emacs
  - EMACS=$HOME/emacs/src/emacs
  matrix:
  - EMACS_VERSION=25.1
  - EMACS_VERSION=25.2
  - EMACS_VERSION=25.3
  - EMACS_VERSION=26.1
  - EMACS_VERSION=snapshot
before_install:
  - make setup
install:
  - make install
script:
  - make test         # test uncompiled
  - make compile
  - make test         # test compiled
