name: test

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  UNDERCOVER_CONFIG: "(\"elsa.el\" \"elsa-*.el\" (:report-format lcov) (:send-report nil))"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        emacs_version:
          - 27.1
          - 27.2
          - 28.1
          - 28.2
          - snapshot
        include:
          - emacs_version: 'snapshot'
            allow_failure: true
    steps:
    - uses: jcs090218/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - uses: emacs-eask/setup-eask@master
      with:
        version: 'snapshot'

    - uses: actions/checkout@v2

    - name: Test
      run: |
        eask install-deps --dev
        eask exec buttercup -L . -L tests

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flag-name: emacs-${{ matrix.emacs_version }}
        parallel: true

    - name: Run tests
      run: |
        eask clean all
        eask package
        eask install
        eask compile

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
